apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: gitlab
---

# -- Create the permissions the ingress needs control over
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-ci
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","read","delete"]
- apiGroups: [""]
  resources: ["pods","pods/exec"]
  verbs: ["create","get","update","delete","list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["*"]
---

# -- Bind the permissions onto the service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-ci
subjects:
- kind: ServiceAccount
  name: gitlab-ci
  namespace: gitlab
---