apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
  namespace: gitlab
  labels:
    app: gitlab
spec:
  serviceName: gitlab
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: gitlab
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
        selector:
          matchLabels:
            volume-name: gitlab-data
    - metadata:
        name: registry-certs
        namespace: gitlab
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Ki
        selector:
          matchLabels:
            volume-name: gitlab-registry-certs
  template:
    metadata:
      labels:
        app: gitlab-web
    spec:
      nodeSelector:
        gitlab: "true"
      initContainers:
        - name: registry-certs
          image: alpine:latest
          command:
            - sh
            - "-c"
            - |
              apk --no-cache add openssl
              cd /certs
              find /certs -type f -delete
              echo "Create Signing Key and CSR"
              openssl req -nodes -newkey rsa:2048 -keyout registry.key -out registry.csr -subj "/CN=gitlab-issuer"
              echo "Self-Sign Certificate"
              openssl x509 -in registry.csr -out registry.crt -req -signkey registry.key -days 3650
              chmod -v 777 /certs/*
          volumeMounts:
            - name: registry-certs
              mountPath: /certs
      containers:
        - name: gitlab
          image: sameersbn/gitlab:11.3.0
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: web
            - configMapRef:
                name: postgres
            - secretRef:
                name: web
            - secretRef:
                name: postgres
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 22
              name: ssh
              protocol: TCP
          resources:
            limits:
              cpu: "1000m"
              memory: "4Gi"
            requests:
              cpu: "250m"
              memory: "500Mi"
          volumeMounts:
            - name: data
              mountPath: /home/git/data
            - name: registry-certs
              mountPath: /certs
---

# -- Service for the Ingress to target
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: gitlab
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab-web
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: ssh
      port: 10022
      targetPort: 22
